### ISSUE TITLE
8: Robot walks over ball instead of kicking it

### ISSUE THREAD

**Issue by froschy** [01rfcberlin/robocup-blockly#37] opened 2021-04-17 16:56 UTC
![grafik](https://user-images.githubusercontent.com/69001402/115120599-9d78d600-9fae-11eb-9f26-33e8b8373d7c.png)

**Comment by MaikePaetzel** [comment] 2021-04-17 17:26
Duplicate of #32 
this is a problem of the "Roboter am Ball" block which doesn't behave correctly yet

**Closed as completed by MaikePaetzel** 2021-04-17 17:26 UTC
Labels: bug
